spring.application.name=service-product
server.port=8010

spring.cloud.nacos.server-addr=127.0.0.1:8848

# spring.config.import=nacos:service-product.properties
spring.nacos.config.import-check.enabled=false
