server:
  port: 8080

spring:
  profiles:
    active: dev
    include: feign #会激活application-feign.yml（Feign 特定配置）
  application:
    name: service-order
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        namespace: ${spring.profiles.active:public}
        import-check:
          enabled: false # 必须写，因为上面的是默认配置，默认没有配置
logging:
  level:
    com.cyy.order.feign: debug #feign客户端所在的包名com/cyy/order/feign
---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
    activate:
      on-profile: test
---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
    activate:
      on-profile: prod
---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
    activate:
      on-profile: dev